BrickSchema/brick-website

src/layouts/Apps.vue
src/layouts/Categories.vue
src/pages/Tools.vue
src/templates/Category.vue

Reverts BrickSchema/brick-website#19

Revert "Horizontal tool-cards"

---

src/layouts/Apps.vue
src/layouts/Categories.vue
src/pages/Tools.vue
src/templates/Category.vue

Reverts BrickSchema/brick-website#20

Horizontal tool-cards

---

.gitignore
gridsome.server.js
src/components/RecursiveTree.vue
src/components/TagSetSearchInput.vue
src/templates/TagSet.vue

Tree View for TagSets

---

webpages/get-started.md

Little unsure on the formatting, but let me know what you all think of content!

Getting started page refactorization

---

gridsome.server.js
src/components/RecursiveTree.vue
src/components/SearchInput.vue
src/components/TagSetSearchInput.vue

Support other prefixPaths 
This affects both the search inputs and the recursive tree
Fixes #34

Fix website serving path

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/content-request.md
.github/ISSUE_TEMPLATE/feature_request.md

Update issue templates

---

gridsome.config.js
webpages/about.md

This embeds the webinar youtube video before the "Learn more" section of the homepage.
[Preview](https://brickschema.netlify.com/)
Release note: None

Add webinar video to homepage

---

static/schema/1.0.3/Brick.ttl
static/schema/1.0.3/BrickFrame.ttl
static/schema/1.0.3/BrickTag.ttl
static/schema/1.0.3/BrickUse.ttl

This is urgent. The ttl files for 1.0.3 schema is wrong as they're actually 1.0.2. Please merge this ASAP.

fix the wrong version in schema files

---

blog/press_releases.md

Add AutomatedBuildings.com Interview

---

src/pages/Community.vue
webpages/grants-and-awards.md

- name on the Grants page
- link on the Community page

Update JCI details

---

src/components/OntologySearchInput.vue

Fixes: Display issue with ontology search feature (#74)

Fix ontology search results

---

blog/brick-and-vbis.md
src/layouts/Default.vue
webpages/press-releases.md

@shreyasnagare is there a way to edit the order of the navbar headings so that press releases can go later?

Add press release page w/ VBIS

---

webpages/relationships.md

* Fix minor typos
* Update inverse relationships table

Fix typos in relationships page

---

src/components/ClassNode.vue
src/components/RelationshipNode.vue
src/templates/Class.vue
src/templates/Relationship.vue

Fix IRI anchor tags

---

static/schema/1.1.1/Brick.ttl
webpages/resources.md

Prepping for v1.2 release coming in the next few weeks.
Started to organize the page so that v1.1 releases can be found together
**TODO**: how to generate documentation for v1.1.1 (can be listed under v1.1 on the documentation page)

Adding v1.1.1 to the webpage

---

blog/brick-consortium-kickoff-2021.md
gridsome.config.js
webpages/consortium.md

The youtube plugin doesn't give me a preview on this page, but I'm not sure why. It works fine on about.md but not this one, even if I use the same video. I'm hopeful that maybe the netlify preview will come out right

update for consortium kickoff recording. 

---

blog/working-groups.md

Update times, add Google Calendar links

Update Working Group Info

---

blog/working-groups.md

moving from meet -> Zoom + office hours

Update working group links

---

blog/working-groups.md

The text in the working group post was out of date, so this updates that to match

update text to match new calendar

---

src/pages/Community.vue

add Carrier & SE to places being used, move JCI out of collaborators, since the consortium has made everyone collaborators

update community pages 
